--- lib-python/2.7/test/test_urllib2.py	2015-04-18 05:34:44.691111369 +0300
+++ Lib/test/test_urllib2.py	2015-04-18 05:34:31.875089913 +0300
@@ -663,6 +663,11 @@
             self.assertEqual(headers.get("Content-type"), mimetype)
             self.assertEqual(int(headers["Content-length"]), len(data))
 
+    # This test isn't working on Ubuntu on an Apple Intel powerbook,
+    # Jython 2.7b1+ (default:6b4a1088566e, Feb 10 2013, 14:36:47) 
+    # [OpenJDK 64-Bit Server VM (Oracle Corporation)] on java1.7.0_09
+    @unittest.skipIf(test_support.is_jython,
+                     "FIXME: Currently not working on jython")
     def test_file(self):
         import rfc822, socket
         h = urllib2.FileHandler()
@@ -1347,6 +1352,7 @@
         'something bad happened'
         """
 
+    @unittest.skip("Test is broken because of fp=None, which causes failure to call addinfourl superclass __init__")
     def test_HTTPError_interface_call(self):
         """
         Issue 15701= - HTTPError interface has info method available from URLError.
